name: UPM Sync
on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Config
        run: |
          git config --local user.email "contact@gameworkstore.com"
          git config --local user.name "game-workstore-bot"
      
      - name: Update internals
        id: updated
        run: |
          READMECMP=cmp --silent "README.md" "Assets/Package/README.md"
          if [ ! $READMECMP ]
          then
            echo "they are different"
          fi
          echo "::set-output name=required::false"

      - name: Push changes
        if: ${{ steps.updated.outputs.required }}
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main

      - name: Cook UPM
        run: |
          git subtree split -P Assets/Package/ -b upm
          git checkout upm
          ls

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: upm
          force: true